In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from matplotlib.pyplot import plot

In [ ]:
df = pd.read_csv('data/archive/sign_mnist/sign_mnist.csv')

In [ ]:
df

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,3,107,118,127,134,139,143,146,150,153,...,207,207,207,207,206,206,206,204,203,202
1,6,155,157,156,156,156,157,156,158,158,...,69,149,128,87,94,163,175,103,135,149
2,2,187,188,188,187,187,186,187,188,187,...,202,201,200,199,198,199,198,195,194,195
3,2,211,211,212,212,211,210,211,210,210,...,235,234,233,231,230,226,225,222,229,163
4,13,164,167,170,172,176,179,180,184,185,...,92,105,105,108,133,163,157,163,164,179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27450,13,189,189,190,190,192,193,193,193,193,...,132,165,99,77,52,200,234,200,222,225
27451,23,151,154,157,158,160,161,163,164,166,...,198,198,198,198,198,196,195,195,195,194
27452,18,174,174,174,174,174,175,175,174,173,...,121,196,209,208,206,204,203,202,200,200
27453,17,177,181,184,185,187,189,190,191,191,...,119,56,27,58,102,79,47,64,87,93
27454,23,179,180,180,180,182,181,182,183,182,...,108,132,170,194,214,203,197,205,209,215

In [ ]:
label_unique = df.label.unique()
label_unique.sort()
print(label_unique)

[ 0  1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

In [ ]:
print(df.label.value_counts()/df.label.sum())
expected = df.label.value_counts().sum()/label_unique.shape
print(f'Математическое ожидание: {expected[0]}')
disp = (df.label.value_counts().max() - df.label.value_counts().min())/df.label.value_counts().max()
print(f'Расстояние в %: {disp}')

label
17    0.003826
16    0.003782
11    0.003669
22    0.003622
5     0.003560
18    0.003545
3     0.003536
14    0.003536
19    0.003507
23    0.003442
8     0.003436
20    0.003433
13    0.003403
2     0.003382
0     0.003329
24    0.003306
10    0.003294
6     0.003223
15    0.003217
21    0.003199
12    0.003119
7     0.002995
1     0.002986
4     0.002830
Name: count, dtype: float64
Математическое ожидание: 1143.9583333333333
Расстояние в %: 0.2604327666151468

In [ ]:
X_data, X_valid, y_data, y_valid = train_test_split(df.drop(['label'], axis=1), df['label'], test_size=0.1, random_state=78)

In [ ]:
valid = pd.concat([y_valid, X_valid], axis=1)
dataset = pd.concat([y_data, X_data], axis=1)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(['label'], axis=1), df['label'], test_size=0.2, random_state=78)

In [ ]:
train = pd.concat([y_train, X_train], axis=1)
test = pd.concat([y_test, X_test], axis=1)

In [ ]:
print(valid.shape)
print(test.shape)
print(train.shape)

(2746, 785)
(5491, 785)
(21964, 785)

In [ ]:
print(valid.label.value_counts()/valid.label.sum())
disp = (valid.label.value_counts().max() - valid.label.value_counts().min())/valid.label.value_counts().max()
print(f'Расстояние в %: {disp}')

label
8     0.004000
16    0.004000
17    0.003848
0     0.003818
3     0.003727
7     0.003727
2     0.003697
11    0.003667
19    0.003636
22    0.003576
23    0.003576
15    0.003545
14    0.003515
5     0.003485
21    0.003394
20    0.003303
10    0.003242
12    0.003212
6     0.003212
4     0.003151
13    0.003121
1     0.003030
18    0.002909
24    0.002818
Name: count, dtype: float64
Расстояние в %: 0.29545454545454547

In [ ]:
print(test.label.value_counts()/test.label.sum())
disp = (test.label.value_counts().max() - test.label.value_counts().min())/test.label.value_counts().max()
print(f'Расстояние в %: {disp}')

label
11    0.004001
16    0.003956
8     0.003895
3     0.003849
2     0.003789
17    0.003743
0     0.003743
14    0.003637
19    0.003546
23    0.003486
10    0.003471
15    0.003410
5     0.003410
12    0.003365
20    0.003304
7     0.003274
13    0.003274
6     0.003274
18    0.003258
22    0.003228
21    0.003198
24    0.003077
4     0.003046
1     0.002986
Name: count, dtype: float64
Расстояние в %: 0.2537878787878788

In [ ]:
print(train.label.value_counts()/train.label.sum())
disp = (train.label.value_counts().max() - train.label.value_counts().min())/train.label.value_counts().max()
print(f'Расстояние в %: {disp}')

label
17    0.003846
16    0.003739
22    0.003717
18    0.003615
5     0.003596
11    0.003589
14    0.003512
19    0.003497
20    0.003464
3     0.003460
13    0.003435
23    0.003431
24    0.003361
8     0.003324
2     0.003284
10    0.003251
0     0.003229
6     0.003211
21    0.003200
15    0.003170
12    0.003060
1     0.002986
7     0.002928
4     0.002777
Name: count, dtype: float64
Расстояние в %: 0.27793696275071633

In [ ]:
valid.to_csv('valid.csv', index=False)
test.to_csv('test.csv', index=False)
train.to_csv('train.csv', index=False)